language: node_js
node_js:
  - "8"
script:
  - npm run test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
